# Server configuration
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mysql
    username: root
    password: assamo
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
    returnInstanceForEmptyRow: true
    mapper-locations: com/example/**/*.xml
    type-aliases-package: com.example.**.dto

springdoc:
  api-docs.path: /api-docs
  packages-to-scan: 
    - com.example
  default-consumes-media-type: application/json
  default-produces-media-type: application/json  